# Generated by Django 5.2.9 on 2026-09-09 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaria', '0017_pedido_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='motoqueiro',
            field=models.ForeignKey(blank=True, help_text='Entregador responsável', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas_motoqueiro', to=settings.AUTH_USER_MODEL),
        ),
    ]
