# Generated by Django 5.2.9 on 2026-09-15 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaria', '0021_itempedido_borda_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='observacao',
            field=models.TextField(blank=True, default=''),
        ),
    ]
