# Generated by Django 5.2.9 on 2026-09-16 00:21

import pizzaria.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaria', '0022_itempedido_observacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoPreco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_p', models.DecimalField(decimal_places=2, default=25, max_digits=6)),
                ('preco_m', models.DecimalField(decimal_places=2, default=32, max_digits=6)),
                ('preco_g', models.DecimalField(decimal_places=2, default=39, max_digits=6)),
                ('especial_parcial_p', models.DecimalField(decimal_places=2, default=2, max_digits=6)),
                ('especial_parcial_m', models.DecimalField(decimal_places=2, default=3, max_digits=6)),
                ('especial_parcial_g', models.DecimalField(decimal_places=2, default=4, max_digits=6)),
                ('especial_total_p', models.DecimalField(decimal_places=2, default=4, max_digits=6)),
                ('especial_total_m', models.DecimalField(decimal_places=2, default=6, max_digits=6)),
                ('especial_total_g', models.DecimalField(decimal_places=2, default=8, max_digits=6)),
                ('borda_catupiry_p', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('borda_catupiry_m', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('borda_catupiry_g', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('borda_cheddar_p', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('borda_cheddar_m', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('borda_cheddar_g', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('borda_catupiry_original_p', models.DecimalField(decimal_places=2, default=10, max_digits=6)),
                ('borda_catupiry_original_m', models.DecimalField(decimal_places=2, default=12, max_digits=6)),
                ('borda_catupiry_original_g', models.DecimalField(decimal_places=2, default=14, max_digits=6)),
                ('borda_chocolate_p', models.DecimalField(decimal_places=2, default=6, max_digits=6)),
                ('borda_chocolate_m', models.DecimalField(decimal_places=2, default=8, max_digits=6)),
                ('borda_chocolate_g', models.DecimalField(decimal_places=2, default=10, max_digits=6)),
                ('catupiry_cima_metade_p', models.DecimalField(decimal_places=2, default=5, max_digits=6)),
                ('catupiry_cima_metade_m', models.DecimalField(decimal_places=2, default=6, max_digits=6)),
                ('catupiry_cima_metade_g', models.DecimalField(decimal_places=2, default=7, max_digits=6)),
                ('catupiry_cima_inteira_p', models.DecimalField(decimal_places=2, default=10, max_digits=6)),
                ('catupiry_cima_inteira_m', models.DecimalField(decimal_places=2, default=12, max_digits=6)),
                ('catupiry_cima_inteira_g', models.DecimalField(decimal_places=2, default=14, max_digits=6)),
            ],
            bases=(pizzaria.utils.SanitizedModelMixin, models.Model),
        ),
    ]
